version: '3.8'
services:
 todo_api:
    container_name: todo_api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
    depends_on:
      - mysql
    networks:
      - todoNetwork

 todo_front:
    container_name: todo_front
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
    networks:
      - todoNetwork
    depends_on:
      - todo_api

    

 mysql:
    image: arm64v8/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - todoNetwork

networks:
    todoNetwork:
      driver: bridge
